"""added photo to likes

Revision ID: dd254a8bd816
Revises: 8fa88b8bd508
Create Date: 2025-12-02 18:01:04.646617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd254a8bd816'
down_revision: Union[str, Sequence[str], None] = '8fa88b8bd508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
